# Generated by Django 6.0.5 on 2026-05-30 04:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wastage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(choices=[('expired', 'Expired'), ('damaged', 'Damaged'), ('returned', 'Returned'), ('overproduction', 'Overproduction'), ('quality_issue', 'Quality Issue'), ('other', 'Other')], max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('loss', models.DecimalField(db_index=True, decimal_places=2, help_text='Total loss (quantity * unit_cost)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wastages', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastages', to='products.product')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastage_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wastage',
                'verbose_name_plural': 'Wastages',
                'db_table': 'wastage_wastage',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='wastage_was_date_acc31f_idx'), models.Index(fields=['product', 'date'], name='wastage_was_product_e5f9b3_idx'), models.Index(fields=['reason'], name='wastage_was_reason_0a52c8_idx'), models.Index(fields=['is_approved'], name='wastage_was_is_appr_203f12_idx')],
            },
        ),
    ]
