# Generated by Django 4.2.11 on 2026-06-03 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_cost_price_product_max_stock_limit_and_more"),
        ("wastage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastage",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wastages",
                to="products.productbatch",
            ),
        ),
    ]
