# Generated by Django 4.2.11 on 2026-06-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("salesperson", "Salesperson"),
                    ("factory_distributor", "Factory Distributor"),
                    ("customer", "Customer"),
                ],
                db_index=True,
                default="salesperson",
                max_length=20,
            ),
        ),
    ]
