# Generated by Django 4.2.11 on 2026-06-03 15:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cost price per unit",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="max_stock_limit",
            field=models.IntegerField(
                default=100,
                help_text="Maximum stock limit for outlets",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                default="piece", help_text="Product unit of measurement", max_length=50
            ),
        ),
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "batch_number",
                    models.CharField(
                        db_index=True, help_text="Batch identifier", max_length=100
                    ),
                ),
                ("production_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "quantity_produced",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "current_quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "outlet_assignment",
                    models.CharField(
                        blank=True,
                        help_text="Outlet or location assigned to this batch",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Batch",
                "verbose_name_plural": "Product Batches",
                "db_table": "products_productbatch",
                "ordering": ["-production_date", "batch_number"],
                "indexes": [
                    models.Index(
                        fields=["product", "batch_number"],
                        name="products_pr_product_613377_idx",
                    ),
                    models.Index(
                        fields=["current_quantity"],
                        name="products_pr_current_f003f9_idx",
                    ),
                ],
            },
        ),
    ]
