# Generated by Django 4.2.11 on 2026-06-04 02:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_outlet_product_max_outlet_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispatch",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dispatchrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="outlet",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="productbatch",
            options={"ordering": ["expiry_date", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="stockadjustment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_categor_50f5f1_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_stock_4d23d5_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_sku_ca0cdc_idx",
        ),
        migrations.RemoveIndex(
            model_name="productbatch",
            name="products_pr_product_613377_idx",
        ),
        migrations.RemoveIndex(
            model_name="productbatch",
            name="products_pr_current_f003f9_idx",
        ),
        migrations.RemoveIndex(
            model_name="stockadjustment",
            name="products_st_product_6a066a_idx",
        ),
        migrations.RemoveIndex(
            model_name="stockadjustment",
            name="products_st_reason_66a8c0_idx",
        ),
        migrations.RemoveField(
            model_name="dispatch",
            name="dispatched_at",
        ),
        migrations.RemoveField(
            model_name="dispatch",
            name="dispatched_by",
        ),
        migrations.RemoveField(
            model_name="dispatchrequest",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="dispatchrequest",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="dispatchrequest",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="dispatchrequest",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="address",
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="product",
            name="cost_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="max_outlet_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="stockadjustment",
            name="adjusted_by",
        ),
        migrations.RemoveField(
            model_name="stockadjustment",
            name="sale",
        ),
        migrations.RemoveField(
            model_name="stockadjustment",
            name="wastage",
        ),
        migrations.AddField(
            model_name="dispatch",
            name="driver_name",
            field=models.CharField(default="Unassigned", max_length=255),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.outlet",
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("packed", "Packed"),
                    ("en_route", "En Route"),
                    ("delivered", "Delivered"),
                ],
                default="packed",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="outlet",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="outlet",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="measurement_type",
            field=models.CharField(default="units", max_length=50),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productbatch",
            ),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.dispatchrequest",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchrequest",
            name="outlet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatch_requests",
                to="products.outlet",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchrequest",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AlterField(
            model_name="dispatchrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="outlet",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="max_stock_limit",
            field=models.IntegerField(
                default=100, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_stock",
            field=models.IntegerField(
                default=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shelf_life_days",
            field=models.IntegerField(
                default=3, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="productbatch",
            name="batch_number",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="productbatch",
            name="current_quantity",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="productbatch",
            name="expiry_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="productbatch",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="productbatch",
            name="outlet_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.outlet",
            ),
        ),
        migrations.AlterField(
            model_name="productbatch",
            name="quantity_produced",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="reason",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name="dispatchrequest",
            table="products_dispatch_request",
        ),
        migrations.AlterModelTable(
            name="productbatch",
            table="products_batch",
        ),
    ]
