# Generated by Django 4.2.11 on 2026-06-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0005_alter_dispatch_options_alter_dispatchrequest_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productbatch",
            name="batch_number",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="productbatch",
            constraint=models.UniqueConstraint(
                fields=("product", "batch_number"), name="unique_product_batch_sequence"
            ),
        ),
    ]
