# Generated by Django 4.2.11 on 2026-06-05 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_stockadjustment_adjusted_by_stockadjustment_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockadjustment",
            name="adjusted_by",
        ),
        migrations.RemoveField(
            model_name="stockadjustment",
            name="sale",
        ),
    ]
