# Generated by Django 4.2.11 on 2026-06-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_remove_stockadjustment_adjusted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="target_stock",
            field=models.IntegerField(default=50),
        ),
    ]
