# Generated by Django 4.2.11 on 2026-06-08 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_stockadjustment_adjusted_by_stockadjustment_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(
                db_index=True,
                default=100,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
