# Generated by Django 4.2.11 on 2026-06-04 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_order_payment_orderitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-pickup_date", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="saleitem",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="sales_order_order_n_1515f9_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="sales_order_status_2602a7_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="sales_order_payment_ca014c_idx",
        ),
        migrations.RemoveIndex(
            model_name="sale",
            name="sales_sale_date_ca4177_idx",
        ),
        migrations.RemoveIndex(
            model_name="sale",
            name="sales_sale_cashier_1c82a7_idx",
        ),
        migrations.RemoveIndex(
            model_name="sale",
            name="sales_sale_is_void_ce8dca_idx",
        ),
        migrations.RemoveIndex(
            model_name="saleitem",
            name="sales_item_sale_id_dd0886_idx",
        ),
        migrations.RemoveIndex(
            model_name="saleitem",
            name="sales_item_product_d9aeda_idx",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_number",
            new_name="reference_number",
        ),
        migrations.RemoveField(
            model_name="order",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="outlet",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="order",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paid_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_reference",
        ),
        migrations.AddField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(default="cash", max_length=50),
        ),
        migrations.AddField(
            model_name="payment",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="pickup_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("packed", "Packed"),
                    ("ready", "Ready for Pickup"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("check", "Check"),
                    ("online", "Online"),
                ],
                default="cash",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
